sudo: required
services:
- docker
before_install:
- docker build -t mandiberg-painting .
- git config --local user.name "Travis CI"
- git config --local user.email "ben@lerchin.com"
- git checkout master
- git remote rm origin
- git remote add origin "https://blerchin:$GITHUB_TOKEN@github.com/blerchin/mandiberg-painting.git"
script:
- docker run -v $(pwd)/data:/root/mandiberg-painting/data -e API_KEY -e CHANNEL_ID
  mandiberg-painting python getYoutube.py
- export TIMESTAMP=$(date +'%Y%m%d-%H%M%S')
- git add -u
- git commit -m "Adding results on $TIMESTAMP"
- git push origin master
